//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.EventResource", typeof(EventResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno kreiranje sertifikata bez pvk-a &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateCreated {
            get {
                return ResourceManager.GetString("CertificateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspesno kreiranje sertifikata bez pvk-a &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateFailed {
            get {
                return ResourceManager.GetString("CertificateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno kreiranje sertifikata sa pvk-om &apos;{0}&apos;.
        /// </summary>
        internal static string CertificatePasswordCreated {
            get {
                return ResourceManager.GetString("CertificatePasswordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspesno kreiranje sertifikata sa pvk-om &apos;{0}&apos;.
        /// </summary>
        internal static string CertificatePasswordFailed {
            get {
                return ResourceManager.GetString("CertificatePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno replicirani sertifikati &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateReplicated {
            get {
                return ResourceManager.GetString("CertificateReplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno povlacenje sertifikata &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateRevoked {
            get {
                return ResourceManager.GetString("CertificateRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno repliciranje povucenih sertifikata &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateRevokedReplicated {
            get {
                return ResourceManager.GetString("CertificateRevokedReplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspesno povlacenje sertifikata &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateRevokeFailed {
            get {
                return ResourceManager.GetString("CertificateRevokeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno instaliran sertifikat bez pvk-a &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateWithoutPvkInstallationSuccess {
            get {
                return ResourceManager.GetString("CertificateWithoutPvkInstallationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno instaliran sertifikat sa pvk-om &apos;{0}&apos;.
        /// </summary>
        internal static string CertificateWithPvkInstallationSuccess {
            get {
                return ResourceManager.GetString("CertificateWithPvkInstallationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno zatvaranje klijentske konekcije &apos;{0}&apos;.
        /// </summary>
        internal static string ClientConnectionClosed {
            get {
                return ResourceManager.GetString("ClientConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno uspostavljanje konekcije &apos;{0}&apos;.
        /// </summary>
        internal static string ClientConnectionOpen {
            get {
                return ResourceManager.GetString("ClientConnectionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno zatvaranje serverske konekcije &apos;{0}&apos;.
        /// </summary>
        internal static string ServerConnectionClosed {
            get {
                return ResourceManager.GetString("ServerConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno uspostavljanje konekcije &apos;{0}&apos;.
        /// </summary>
        internal static string ServerConnectionOpen {
            get {
                return ResourceManager.GetString("ServerConnectionOpen", resourceCulture);
            }
        }
    }
}
